package org.usfirst.frc2408.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2408.robot.Robot;

/**
 *
 */
public class Rotate extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Rotate() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.turn);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double turnstick = Robot.oi.stick.getRawAxis(3);
    	double FRTEQ = 1.25*(turnstick)+2.78;
    	double FLTEQ = 1.25*(turnstick)+3.;
    	double BRTEQ = 1.25*(turnstick)+2.94;
    	double BLTEQ = 1.25*(turnstick)+3.07;
    	
    	
    	Robot.turn.rBT.set(Robot.turn.BREV - BRTEQ);
    	Robot.turn.rFT.set(Robot.turn.FREV - FRTEQ);
    	Robot.turn.lBT.set(Robot.turn.BLEV - BLTEQ);
    	Robot.turn.lFT.set(Robot.turn.FLEV - FLTEQ);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
