package org.usfirst.frc2408.robot.subsystems;

import org.usfirst.frc2408.robot.RobotMap;
import org.usfirst.frc2408.robot.commands.*;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Turn extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public final SpeedController lFT = RobotMap.turnLFT;
    public final SpeedController rFT = RobotMap.turnRFT;
    public final SpeedController lBT = RobotMap.turnLBT;
    public final SpeedController rBT = RobotMap.turnRBT;
    private final RobotDrive sTrain = RobotMap.turnsTrain;
    private final AnalogInput lFTE = RobotMap.turnLFTE;
    private final AnalogInput rFTE = RobotMap.turnRFTE;
    private final AnalogInput lBTE = RobotMap.turnLBTE;
    private final AnalogInput rBTE = RobotMap.turnRBTE;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public double FLEV = lFTE.getAverageVoltage();
    public double BLEV = lBTE.getAverageVoltage();
    public double FREV = rFTE.getAverageVoltage();
    public double BREV = rBTE.getAverageVoltage();


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Rotate());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

